// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/helium12/geek-go/week04/examples/market/internal/biz"
	"github.com/helium12/geek-go/week04/examples/market/internal/conf"
	"github.com/helium12/geek-go/week04/examples/market/internal/data"
	"github.com/helium12/geek-go/week04/examples/market/internal/server"
	"github.com/helium12/geek-go/week04/examples/market/internal/service"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, traceTracerProvider trace.TracerProvider, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(dataData, logger)
	productUsecase := biz.NewProductUsecase(productRepo, logger)
	marketService := service.NewMarketService(productUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, traceTracerProvider, marketService)
	grpcServer := server.NewGRPCServer(confServer, logger, traceTracerProvider, marketService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
